# Generated by Django 2.2 on 2021-07-09 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles%Y/%m/%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MyProfile',
                'verbose_name_plural': 'MyProfile',
            },
        ),
        migrations.CreateModel(
            name='CollegeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=120)),
                ('school_type', models.CharField(max_length=120)),
                ('school_location', models.CharField(max_length=120)),
                ('is_ib_candidate', models.CharField(max_length=120)),
                ('ethnicity', models.CharField(max_length=120)),
                ('major', models.CharField(max_length=120)),
                ('class_rank', models.CharField(max_length=120)),
                ('passout_year', models.CharField(max_length=120)),
                ('weighted_gpa', models.CharField(max_length=120)),
                ('sub_eng_h', models.CharField(max_length=120)),
                ('sub_mat_h', models.CharField(max_length=120)),
                ('sub_sci_h', models.CharField(max_length=120)),
                ('sub_oth_h', models.CharField(max_length=120)),
                ('sub_hist_h', models.CharField(max_length=120)),
                ('sub_arts_h', models.CharField(max_length=120)),
                ('sub_ele_h', models.CharField(max_length=120)),
                ('sat_math', models.CharField(max_length=120)),
                ('sat_ebread', models.CharField(max_length=120)),
                ('sat_wrt_lng', models.CharField(max_length=120)),
                ('sat_scores_from', models.CharField(max_length=120)),
                ('act_comp', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collegedata', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CollegeData',
                'verbose_name_plural': 'CollegeData',
            },
        ),
    ]
