college_list = ['Abilene Christian University',
 'Academy of Art University',
 'Adams State University',
 'Adelphi University',
 'Adrian College',
 'Agnes Scott College',
 'Alabama A&M University',
 'Alabama State University',
 'Alaska Pacific University',
 'Albany College of Pharmacy and Health Sciences',
 'Albany State University',
 'Albertus Magnus College',
 'Albion College',
 'Albright College',
 'Alcorn State University',
 'Alfred State College',
 'Alfred University',
 'Allegheny College',
 'Alma College',
 'Alvernia University',
 'American International College',
 'American University',
 'Amherst College',
 'Anderson University',
 'Andrews University',
 'Angelo State University',
 'Anna Maria College',
 'Antioch University Midwest',
 'Antioch University Santa Barbara',
 'Appalachian State University',
 'Aquinas College',
 'Arcadia University',
 'Argosy University, Phoenix',
 'Arizona State University',
 'Arkansas State University',
 'Arkansas Tech University',
 'Armstrong State University',
 'Art Academy of Cincinnati',
 'Art Center College of Design',
 'Art Institute of California - Inland Empire',
 'Art Institute of California - Orange County',
 'Art Institute of Houston',
 'Art Institute of Pittsburgh',
 'Asbury University',
 'Ashford University',
 'Ashland University',
 'Assumption College',
 'Auburn University',
 'Auburn University at Montgomery',
 'Augsburg College',
 'Augustana College',
 'Augustana University',
 'Aurora University',
 'Austin College',
 'Austin Peay State University',
 'Ave Maria University',
 'Averett University',
 'Avila University',
 'Azusa Pacific University',
 'Babson College',
 'Baker College of Flint',
 'Baker University',
 'Baldwin Wallace University',
 'Ball State University',
 'Baptist Bible College',
 'Barclay College',
 'Bard College',
 "Bard College at Simon's Rock",
 'Barnard College',
 'Barry University',
 'Barton College',
 'Baruch College (City University of New York)',
 'Bates College',
 'Bay Path College',
 'Bayamon Central University',
 'Baylor University',
 'Becker College',
 'Belhaven University',
 'Bellarmine University',
 'Belmont Abbey College',
 'Belmont University',
 'Beloit College',
 'Bemidji State University',
 'Benedict College',
 'Benedictine College',
 'Benedictine University',
 'Bennett College',
 'Bennington College',
 'Bentley University',
 'Berea College',
 'Berkeley College',
 'Berklee College of Music',
 'Berry College',
 'Bethany College',
 'Bethany Lutheran College',
 'Bethel College',
 'Bethel University',
 'Bethune-Cookman University',
 'Binghamton University',
 'Biola University',
 'Birmingham-Southern College',
 'Black Hills State University',
 'Blackburn College',
 'Bloomfield College',
 'Bloomsburg University of Pennsylvania',
 'Blue Mountain College',
 'Bluefield College',
 'Bluefield State College',
 'Bluffton University',
 'Bob Jones University',
 'Boise State University',
 'Boston College',
 'Boston University',
 'Bowdoin College',
 'Bowie State University',
 'Bowling Green State University',
 'Bradley University',
 'Brandeis University',
 'Brenau University',
 'Brescia University',
 'Brevard College',
 'Brewton-Parker College',
 'Briar Cliff University',
 'Bridgewater College',
 'Bridgewater State University',
 'Brigham Young University',
 'Brigham Young University - Hawaii',
 'Brigham Young University - Idaho',
 'Brooklyn College (City University of New York)',
 'Brooks Institute',
 'Brown University',
 'Bryan College',
 'Bryant & Stratton College - Parma Campus',
 'Bryant University',
 'Bryn Athyn College',
 'Bryn Mawr College',
 'Bucknell University',
 'Buena Vista University',
 'Buffalo State College',
 'Butler University',
 'Cabrini College',
 'Cairn University',
 'Caldwell University',
 'California Baptist University',
 'California College of the Arts',
 'California Institute of Technology',
 'California Institute of the Arts',
 'California Lutheran University',
 'California Maritime Academy',
 'California Polytechnic State University, San Luis Obispo',
 'California State Polytechnic University, Pomona',
 'California State University Bakersfield',
 'California State University Channel Islands',
 'California State University Chico',
 'California State University Dominguez Hills',
 'California State University East Bay',
 'California State University Fresno',
 'California State University Fullerton',
 'California State University Long Beach',
 'California State University Los Angeles',
 'California State University Monterey Bay',
 'California State University Northridge',
 'California State University Sacramento',
 'California State University San Bernardino',
 'California State University San Marcos',
 'California State University Stanislaus',
 'California University of Pennsylvania',
 'Calvin College',
 'Campbell University',
 'Campbellsville University',
 'Canisius College',
 'Capital University',
 'Cardinal Stritch University',
 'Carleton College',
 'Carlow University',
 'Carnegie Mellon University',
 'Carroll College',
 'Carroll University',
 'Carson-Newman University',
 'Carthage College',
 'Case Western Reserve University',
 'Castleton State College',
 'Catawba College',
 'Catholic University of America',
 'Cazenovia College',
 'Cedar Crest College',
 'Cedarville University',
 'Centenary College',
 'Centenary College of Louisiana',
 'Central College',
 'Central Connecticut State University',
 'Central Methodist University',
 'Central Michigan University',
 'Central Penn College',
 'Central State University',
 'Central Washington University',
 'Centre College',
 'Chadron State College',
 'Chamberlain College of Nursing',
 'Chaminade University of Honolulu',
 'Champlain College',
 'Chapman University',
 'Charleston Southern University',
 'Chatham University',
 'Chestnut Hill College',
 'Cheyney University of Pennsylvania',
 'Chicago State University',
 'Chowan University',
 'Christian Brothers University',
 'Christopher Newport University',
 'City College of New York',
 'Claflin University',
 'Claremont McKenna College',
 'Clarion University of Pennsylvania',
 'Clark Atlanta University',
 'Clark University',
 'Clarke University',
 'Clarkson University',
 'Clayton State University',
 'Clemson University',
 'Cleveland Institute of Art',
 'Cleveland Institute of Music',
 'Cleveland State University',
 'Coastal Carolina University',
 'Coe College',
 'Coker College',
 'Colby College',
 'Colby-Sawyer College',
 'Colgate University',
 'College at Brockport',
 'College at Old Westbury',
 'College for Creative Studies',
 'College of Charleston',
 'College of Coastal Georgia',
 'College of Idaho',
 'College of Mount St. Joseph',
 'College of Mount St. Vincent',
 'College of New Rochelle',
 'College of Saint Benedict',
 'College of St. Elizabeth',
 'College of St. Rose',
 'College of St. Scholastica',
 'College of Staten Island (City University of New York)',
 'College of William and Mary',
 'College of Wooster',
 'College of the Atlantic',
 'College of the Holy Cross',
 'Colorado Christian University',
 'Colorado College',
 'Colorado Mesa University',
 'Colorado School of Mines',
 'Colorado State University',
 'Colorado State University - Pueblo',
 'Columbia College',
 'Columbia College Chicago',
 'Columbia University',
 'Columbia University, School of General Studies',
 'Columbus College of Art and Design',
 'Columbus State University',
 'Concord University',
 'Concordia College',
 'Concordia College Alabama',
 'Concordia College New York',
 'Concordia University Ann Arbor',
 'Concordia University Chicago',
 'Concordia University Irvine',
 'Concordia University Nebraska',
 'Concordia University Portland',
 'Concordia University St. Paul',
 'Concordia University Texas',
 'Concordia University Wisconsin',
 'Connecticut College',
 'Converse College',
 'Cooper Union for the Advancement of Science and Art',
 'Coppin State University',
 'Corban University',
 'Cornell College',
 'Cornell University',
 'Cornerstone University',
 'Cornish College of the Arts',
 'Covenant College',
 'Creighton University',
 'Culinary Institute of America',
 'Culver-Stockton College',
 'Curry College',
 "D'Youville College",
 'Daemen College',
 'Dakota State University',
 'Dakota Wesleyan University',
 'Dallas Baptist University',
 'Daniel Webster College',
 'Dartmouth College',
 'Davenport University',
 'Davidson College',
 'Davis and Elkins College',
 'DePaul University',
 'DePauw University',
 'DeSales University',
 'DeVry University - Atlanta',
 'DeVry University - Chicago',
 'DeVry University - Columbus',
 'DeVry University - Crystal City',
 'Delaware State University',
 'Delaware Valley University',
 'Delta State University',
 'Denison University',
 'Dickinson College',
 'DigiPen Institute of Technology',
 'Dillard University',
 'Dixie State College',
 'Dominican College',
 'Dominican University',
 'Dominican University of California',
 'Dordt College',
 'Drake University',
 'Drew University',
 'Drexel University',
 'Drury University',
 'Duke University',
 'Duquesne University',
 'Earlham College',
 'East Carolina University',
 'East Stroudsburg University of Pennsylvania',
 'East Tennessee State University',
 'East-West University',
 'Eastern Connecticut State University',
 'Eastern Illinois University',
 'Eastern Kentucky University',
 'Eastern Mennonite University',
 'Eastern Michigan University',
 'Eastern Nazarene College',
 'Eastern New Mexico University',
 'Eastern University',
 'Eastern Washington University',
 'Eckerd College',
 'Edgewood College',
 'Edinboro University',
 'Edward Waters College',
 'Elizabeth City State University',
 'Elizabethtown College',
 'Elmhurst College',
 'Elmira College',
 'Elms College',
 'Elon University',
 'Embry-Riddle Aeronautical University - Daytona Beach',
 'Embry-Riddle Aeronautical University - Prescott',
 'Emerson College',
 'Emmanuel College',
 'Emmaus Bible College',
 'Emory & Henry College',
 'Emory University',
 'Empire State College',
 'Emporia State University',
 'Endicott College',
 'Erskine College',
 'Eugene Lang College The New School for Liberal Arts',
 'Eureka College',
 'Evangel University',
 'Evergreen State College',
 'Excelsior College',
 'Fairfield University',
 'Fairleigh Dickinson University - College at Florham',
 'Fairleigh Dickinson University - Metropolitan Campus',
 'Fairmont State University',
 'Farmingdale State College',
 'Fashion Institute of Technology',
 'Faulkner University',
 'Fayetteville State University',
 'Felician College',
 'Ferris State University',
 'Ferrum College',
 'Fisher College',
 'Fisk University',
 'Fitchburg State University',
 'Five Towns College',
 'Flagler College',
 'Florida Agricultural and Mechanical University',
 'Florida Atlantic University',
 'Florida Career College',
 'Florida Gulf Coast University',
 'Florida Institute of Technology',
 'Florida International University',
 'Florida Memorial University',
 'Florida Southern College',
 'Florida State University',
 'Fontbonne University',
 'Fordham University',
 'Fort Lewis College',
 'Fort Valley State University',
 'Framingham State University',
 'Francis Marion University',
 'Franciscan University of Steubenville',
 'Franklin & Marshall College',
 'Franklin College',
 'Franklin Pierce University',
 'Franklin W. Olin College of Engineering',
 'Freed-Hardeman University',
 'Fresno Pacific University',
 'Frostburg State University',
 'Full Sail University',
 'Furman University',
 'Gallaudet University',
 'Gannon University',
 'Gardner-Webb University',
 'Geneva College',
 'George Fox University',
 'George Mason University',
 'George Washington University',
 'Georgetown College',
 'Georgetown University',
 'Georgia College and State University',
 'Georgia Gwinnett College',
 'Georgia Institute of Technology',
 'Georgia Regents University',
 'Georgia Southern University',
 'Georgia Southwestern State University',
 'Georgia State University',
 'Georgian Court University',
 'Gettysburg College',
 'Globe University - Minneapolis',
 'Gonzaga University',
 'Gordon College',
 'Goshen College',
 'Goucher College',
 'Governors State University',
 'Grace Bible College',
 'Grace College',
 'Grace University',
 'Grambling State University',
 'Grand Canyon University',
 'Grand Valley State University',
 'Green Mountain College',
 'Greensboro College',
 'Greenville College',
 'Grinnell College',
 'Grove City College',
 'Guilford College',
 'Gustavus Adolphus College',
 'Gwynedd-Mercy College',
 'Hamilton College',
 'Hamline University',
 'Hampden-Sydney College',
 'Hampshire College',
 'Hampton University',
 'Hanover College',
 'Hardin-Simmons University',
 'Harding University',
 'Harris-Stowe State University',
 'Harrisburg University of Science and Technology',
 'Hartwick College',
 'Harvard College',
 'Harvey Mudd College',
 'Hastings College',
 'Haverford College',
 'Hawaii Pacific University',
 'Heidelberg University',
 'Henderson State University',
 'Hendrix College',
 'High Point University',
 'Hilbert College',
 'Hillsdale College',
 'Hiram College',
 'Hobart and William Smith Colleges',
 'Hofstra University',
 'Hollins University',
 'Holy Cross College',
 'Holy Family University',
 'Holy Names University',
 'Hood College',
 'Hope College',
 'Hope International University',
 'Houghton College',
 'Houston Baptist University',
 'Howard Payne University',
 'Howard University',
 'Humboldt State University',
 'Hunter College',
 'Huntingdon College',
 'Huntington University',
 'Husson University',
 'Huston-Tillotson University',
 'Idaho State University',
 'Illinois College',
 'Illinois Institute of Technology',
 'Illinois State University',
 'Illinois Wesleyan University',
 'Immaculata University',
 'Indiana Institute of Technology',
 'Indiana State University',
 'Indiana University - Purdue University Fort Wayne',
 'Indiana University - Purdue University Indianapolis',
 'Indiana University Bloomington',
 'Indiana University Kokomo',
 'Indiana University South Bend',
 'Indiana University Southeast',
 'Indiana University of Pennsylvania',
 'Indiana Wesleyan University',
 'International Business College',
 'Iona College',
 'Iowa State University',
 'Iowa Wesleyan College',
 'Ithaca College',
 'Jackson State University',
 'Jacksonville State University',
 'Jacksonville University',
 'James Madison University',
 'Jarvis Christian College',
 'John Brown University',
 'John Carroll University',
 'John Jay College of Criminal Justice',
 'Johns Hopkins University',
 'Johnson & Wales University',
 'Johnson C. Smith University',
 'Johnson State College',
 'Judson College',
 'Judson University',
 'Juilliard School',
 'Juniata College',
 'Kalamazoo College',
 'Kansas State University',
 'Kean University',
 'Keene State College',
 'Kennesaw State University',
 'Kent State University',
 'Kentucky Christian University',
 'Kentucky State University',
 'Kentucky Wesleyan College',
 'Kenyon College',
 'Kettering University',
 'Keuka College',
 'Keystone College',
 'King College',
 "King's College",
 'Knox College',
 'Kutztown University of Pennsylvania',
 'LIM College',
 'LIU Brooklyn',
 'LIU Post',
 'La Roche College',
 'La Salle University',
 'La Sierra University',
 'LaGrange College',
 'Lafayette College',
 'Laguna College of Art + Design',
 'Lake Erie College',
 'Lake Forest College',
 'Lake Superior State University',
 'Lamar University',
 'Lander University',
 'Lane College',
 'Langston University',
 'Lasell College',
 'Lawrence Technological University',
 'Lawrence University',
 'Le Moyne College',
 'LeMoyne-Owen College',
 'LeTourneau University',
 'Lebanon Valley College',
 'Lee University',
 'Lees-McRae College',
 'Lehigh University',
 'Lehman College (City University of New York)',
 'Lenoir-Rhyne University',
 'Lesley University',
 'Lewis & Clark College',
 'Lewis University',
 'Liberty University',
 'Limestone College',
 'Lincoln Memorial University',
 'Lincoln University',
 'Lindenwood University',
 'Lindsey Wilson College',
 'Linfield College',
 'Lipscomb University',
 'Livingstone College',
 'Lock Haven University of Pennsylvania',
 'Longwood University',
 'Loras College',
 'Louisiana State University',
 'Louisiana State University Health Sciences Center',
 'Louisiana State University Shreveport',
 'Louisiana Tech University',
 'Lourdes University',
 'Loyola Marymount University',
 'Loyola University Chicago',
 'Loyola University Maryland',
 'Loyola University New Orleans',
 'Lubbock Christian University',
 'Luther College',
 'Lycoming College',
 'Lynchburg College',
 'Lyndon State College',
 'Lynn University',
 'Lyon College',
 'MacMurray College',
 'Macalester College',
 'Maine College of Art',
 'Maine Maritime Academy',
 'Malone University',
 'Manchester University',
 'Manhattan College',
 'Manhattan School of Music',
 'Manhattanville College',
 'Mansfield University of Pennsylvania',
 'Marian University',
 'Marietta College',
 'Marist College',
 'Marlboro College',
 'Marquette University',
 'Mars Hill University',
 'Marshall University',
 'Mary Baldwin College',
 'Maryland Institute College of Art',
 'Marymount Manhattan College',
 'Marymount University',
 'Maryville College',
 'Maryville University of Saint Louis',
 'Marywood University',
 'Massachusetts College of Art and Design',
 'Massachusetts College of Liberal Arts',
 'Massachusetts College of Pharmacy and Health Sciences',
 'Massachusetts Institute of Technology',
 'Massachusetts Maritime Academy',
 "Master's College",
 'McDaniel College',
 'McKendree University',
 'McMurry University',
 'McNeese State University',
 'Medaille College',
 'Medgar Evers College (City University of New York)',
 'Memphis College of Art',
 'Menlo College',
 'Mercer University',
 'Mercy College',
 'Mercyhurst University',
 'Meredith College',
 'Merrimack College',
 'Messiah College',
 'Methodist University',
 'Metropolitan State University of Denver',
 'Miami University',
 'Michigan State University',
 'Michigan Technological University',
 'Mid-Atlantic Christian University',
 'MidAmerica Nazarene University',
 'Middle Tennessee State University',
 'Middlebury College',
 'Midwestern State University',
 'Miles College',
 'Miller-Motte College',
 'Millersville University of Pennsylvania',
 'Milligan College',
 'Millikin University',
 'Mills College',
 'Millsaps College',
 'Milwaukee Institute of Art & Design',
 'Milwaukee School of Engineering',
 'Minneapolis College of Art and Design',
 'Minnesota School of Business - St. Cloud',
 'Minnesota State University Mankato',
 'Minnesota State University Moorhead',
 'Misericordia University',
 'Mississippi College',
 'Mississippi State University',
 'Mississippi University for Women',
 'Mississippi Valley State University',
 'Missouri Southern State University',
 'Missouri State University',
 'Missouri University of Science and Technology',
 'Missouri Valley College',
 'Missouri Western State University',
 'Mitchell College',
 'Molloy College',
 'Monmouth College',
 'Monmouth University',
 'Monroe College',
 'Montana State University',
 'Montana Tech of the University of Montana',
 'Montclair State University',
 'Montserrat College of Art',
 'Moody Bible Institute',
 'Moore College of Art and Design',
 'Moravian College',
 'Morehead State University',
 'Morehouse College',
 'Morgan State University',
 'Mount Aloysius College',
 'Mount Carmel College of Nursing',
 'Mount Holyoke College',
 'Mount Ida College',
 'Mount Mercy University',
 'Mount Olive College',
 'Mount St. Mary College',
 "Mount St. Mary's University",
 'Mount Vernon Nazarene University',
 'Muhlenberg College',
 'Murray State University',
 'Muskingum University',
 'Nazareth College',
 'Nebraska Wesleyan University',
 'Neumann University',
 'New College of Florida',
 'New England College',
 'New England Conservatory of Music',
 'New England Institute of Technology',
 'New Jersey City University',
 'New Jersey Institute of Technology',
 'New Mexico Highlands University',
 'New Mexico Institute of Mining and Technology',
 'New Mexico State University',
 'New York City College of Technology',
 'New York Institute of Technology',
 'New York University',
 'NewSchool of Architecture & Design',
 'Newberry College',
 'Newbury College',
 'Newman University',
 'Niagara University',
 'Nicholls State University',
 'Nichols College',
 'Norfolk State University',
 'North Carolina A&T State University',
 'North Carolina Central University',
 'North Carolina State University',
 'North Carolina Wesleyan College',
 'North Central College',
 'North Central University',
 'North Dakota State University',
 'North Greenville University',
 'North Park University',
 'Northeastern Illinois University',
 'Northeastern State University',
 'Northeastern University',
 'Northern Arizona University',
 'Northern Illinois University',
 'Northern Kentucky University',
 'Northern Michigan University',
 'Northland College',
 'Northwest Christian University',
 'Northwest Missouri State University',
 'Northwest Nazarene University',
 'Northwest University',
 'Northwestern College',
 'Northwestern State University of Louisiana',
 'Northwestern University',
 'Northwood University',
 'Norwich University',
 'Notre Dame College',
 'Notre Dame de Namur University',
 'Notre Dame of Maryland University',
 'Nova Southeastern University',
 'Nyack College',
 'Oakland City University',
 'Oakland University',
 'Oakwood University',
 'Oberlin College',
 'Occidental College',
 'Oglethorpe University',
 'Ohio Christian University',
 'Ohio Dominican University',
 'Ohio Northern University',
 'Ohio State Universitity at Marion',
 'Ohio State University',
 'Ohio State University at Newark',
 'Ohio University',
 'Ohio Valley University',
 'Ohio Wesleyan University',
 'Oklahoma Baptist University',
 'Oklahoma Christian University',
 'Oklahoma City University',
 'Oklahoma State University',
 'Oklahoma Wesleyan University',
 'Old Dominion University',
 'Olivet Nazarene University',
 'Oral Roberts University',
 'Oregon College of Art & Craft',
 'Oregon State University',
 'Otis College of Art and Design',
 'Otterbein University',
 'Ouachita Baptist University',
 'Our Lady of the Lake University',
 'Pace University',
 'Pacific Lutheran University',
 'Pacific Northwest College of Art',
 'Pacific Union College',
 'Pacific University',
 'Paine College',
 'Palm Beach Atlantic University',
 'Park University',
 'Parsons The New School for Design',
 'Paul Quinn College',
 "Paul Smith's College",
 'Peabody Conservatory of Johns Hopkins University',
 'Penn State Abington',
 'Penn State Altoona',
 'Penn State Beaver',
 'Penn State Berks',
 'Penn State Brandywine',
 'Penn State DuBois',
 'Penn State Erie, The Behrend College',
 'Penn State Fayette, The Eberly Campus',
 'Penn State Greater Allegheny',
 'Penn State Harrisburg',
 'Penn State Hazleton',
 'Penn State Lehigh Valley',
 'Penn State New Kensington',
 'Penn State University Park',
 'Penn State York',
 'Pennsylvania College of Art & Design',
 'Pennsylvania College of Technology',
 'Pepperdine University',
 'Peru State College',
 'Pfeiffer University',
 'Philadelphia University',
 'Philander Smith College',
 'Piedmont College',
 'Pillar College',
 'Pine Manor College',
 'Pittsburg State University',
 'Pitzer College',
 'Plymouth State University',
 'Point Loma Nazarene University',
 'Point Park University',
 'Pomona College',
 'Portland State University',
 'Post University',
 'Prairie View A&M University',
 'Pratt Institute',
 'Presbyterian College',
 'Prescott College',
 'Princeton University',
 'Principia College',
 'Providence College',
 'Purchase College',
 'Purdue University',
 'Purdue University Calumet',
 'Purdue University North Central',
 'Queens College (City University of New York)',
 'Queens University of Charlotte',
 'Quinnipiac University',
 'Radford University',
 'Ramapo College of New Jersey',
 'Randolph College',
 'Randolph-Macon College',
 'Reed College',
 'Regent University',
 'Regis College',
 'Regis University',
 'Reinhardt University',
 'Rensselaer Polytechnic Institute',
 'Rhode Island College',
 'Rhode Island School of Design',
 'Rhodes College',
 'Rice University',
 'Rider University',
 'Ringling College of Art and Design',
 'Ripon College',
 'Rivier University',
 'Roanoke College',
 'Robert Morris University',
 'Roberts Wesleyan College',
 'Rochester College',
 'Rochester Institute of Technology',
 'Rockford University',
 'Rockhurst University',
 'Rocky Mountain College',
 'Rocky Mountain College of Art & Design',
 'Roger Williams University',
 'Rogers State University',
 'Rollins College',
 'Roosevelt University',
 'Rose-Hulman Institute of Technology',
 'Rosemont College',
 'Rowan University',
 'Rutgers, The State University of New Jersey',
 'Rutgers, The State University of New Jersey - Camden',
 'Rutgers, The State University of New Jersey - Newark',
 'Sacred Heart University',
 'Saginaw Valley State University',
 'Saint Anselm College',
 'Saint Francis University',
 "Saint John's University",
 "Saint Joseph's University",
 'Saint Leo University',
 'Saint Louis University',
 "Saint Martin's University",
 "Saint Mary's College",
 "Saint Mary's College of California",
 "Saint Mary's University of Minnesota",
 'Saint Mary-of-the-Woods College',
 "Saint Michael's College",
 "Saint Peter's University",
 'Saint Vincent College',
 'Saint Xavier University',
 'Salem College',
 'Salem International University',
 'Salem State University',
 'Salisbury University',
 'Salve Regina University',
 'Sam Houston State University',
 'Samford University',
 'San Diego Christian College',
 'San Diego State University',
 'San Francisco Art Institute',
 'San Francisco Conservatory of Music',
 'San Francisco State University',
 'San Jose State University',
 'Santa Clara University',
 'Santa Fe University of Art and Design',
 'Sarah Lawrence College',
 'Savannah College of Art and Design',
 'Savannah State University',
 'School of Visual Arts',
 'School of the Art Institute of Chicago',
 'School of the Museum of Fine Arts',
 'Schreiner University',
 'Scripps College',
 'Seattle Pacific University',
 'Seattle University',
 'Seton Hall University',
 'Seton Hill University',
 'Sewanee: University of the South',
 'Shaw University',
 'Shawnee State University',
 'Shenandoah University',
 'Shepherd University',
 'Shimer College',
 'Shippensburg University of Pennsylvania',
 'Shorter University',
 'Siena College',
 'Siena Heights University',
 'Sierra Nevada College',
 'Simmons College',
 'Simpson College',
 'Skidmore College',
 'Slippery Rock University of Pennsylvania',
 'Smith College',
 'Soka University of America',
 'Sonoma State University',
 'South Carolina State University',
 'South Dakota School of Mines and Technology',
 'South Dakota State University',
 'Southeast Missouri State University',
 'Southeastern Louisiana University',
 'Southeastern Oklahoma State University',
 'Southeastern University',
 'Southern Adventist University',
 'Southern Arkansas University',
 'Southern California Institute of Architecture',
 'Southern Connecticut State University',
 'Southern Illinois University Carbondale',
 'Southern Illinois University Edwardsville',
 'Southern Methodist University',
 'Southern New Hampshire University',
 'Southern Oregon University',
 'Southern University and Agricultural and Mechanical College',
 'Southern Utah University',
 'Southern Vermont College',
 'Southern Virginia University',
 'Southern Wesleyan University',
 'Southwest Baptist University',
 'Southwest Minnesota State University',
 'Southwestern Adventist University',
 'Southwestern Oklahoma State University',
 'Southwestern University',
 'Spelman College',
 'Spring Arbor University',
 'Spring Hill College',
 'Springfield College',
 'St. Ambrose University',
 'St. Andrews University',
 "St. Augustine's University",
 'St. Bonaventure University',
 'St. Catherine University',
 'St. Cloud State University',
 "St. Edward's University",
 'St. Francis College',
 "St. Gregory's University",
 'St. John Fisher College',
 "St. John's College",
 "St. John's University",
 "St. Joseph's College",
 "St. Joseph's College - Brooklyn Campus",
 "St. Joseph's College - Long Island Campus",
 "St. Joseph's College of Maine",
 'St. Lawrence University',
 "St. Mary's College of Maryland",
 "St. Mary's University",
 'St. Norbert College',
 'St. Olaf College',
 'St. Thomas Aquinas College',
 'Stanford University',
 'State University of New York College at Cortland',
 'State University of New York College at Geneseo',
 'State University of New York College at Oneonta',
 'State University of New York College at Potsdam',
 'State University of New York College of Agriculture and Technology at Cobleskill',
 'State University of New York College of Environmental Science and Forestry',
 'State University of New York Institute of Technology',
 'State University of New York Maritime College',
 'State University of New York Plattsburgh',
 'State University of New York at Fredonia',
 'State University of New York at New Paltz',
 'State University of New York at Oswego',
 'Stephen F. Austin State University',
 'Stephens College',
 'Sterling College',
 'Stetson University',
 'Stevens Institute of Technology',
 'Stevens-Henager College, Ogden',
 'Stevenson University',
 'Stillman College',
 'Stockton University',
 'Stonehill College',
 'Stony Brook University',
 'Suffolk University',
 'Sul Ross State University',
 'Susquehanna University',
 'Swarthmore College',
 'Sweet Briar College',
 'Syracuse University',
 'Tabor College',
 'Talladega College',
 'Tarleton State University',
 'Taylor University',
 'Temple University',
 'Tennessee State University',
 'Tennessee Technological University',
 'Texas A&M International University',
 'Texas A&M University',
 'Texas A&M University - Commerce',
 'Texas A&M University - Corpus Christi',
 'Texas A&M University - Kingsville',
 'Texas A&M University - Texarkana',
 'Texas Christian University',
 'Texas College',
 'Texas Lutheran University',
 'Texas Southern University',
 'Texas State University',
 'Texas Tech University',
 "Texas Woman's University",
 'The Citadel',
 'The College of New Jersey',
 'The Jewish Theological Seminary',
 "The King's College",
 'Thiel College',
 'Thomas Aquinas College',
 'Thomas College',
 'Thomas More College',
 'Tiffin University',
 'Toccoa Falls College',
 'Tougaloo College',
 'Towson University',
 'Transylvania University',
 'Trevecca Nazarene University',
 'Trine University',
 'Trinity Christian College',
 'Trinity College',
 'Trinity International University',
 'Trinity University',
 'Trinity Washington University',
 'Troy University',
 'Truett-McConnell College',
 'Truman State University',
 'Tufts University',
 'Tulane University',
 'Tusculum College',
 'Tuskegee University',
 'Union College',
 'Union University',
 'United States Air Force Academy',
 'United States Coast Guard Academy',
 'United States Merchant Marine Academy',
 'United States Military Academy',
 'United States Naval Academy',
 'Unity College',
 'University at Albany',
 'University at Buffalo',
 'University of Advancing Technology',
 'University of Akron',
 'University of Alabama',
 'University of Alabama at Birmingham',
 'University of Alabama in Huntsville',
 'University of Alaska Anchorage',
 'University of Alaska Fairbanks',
 'University of Alaska Southeast',
 'University of Arizona',
 'University of Arkansas',
 'University of Arkansas at Fort Smith',
 'University of Arkansas at Little Rock',
 'University of Arkansas at Monticello',
 'University of Arkansas at Pine Bluff',
 'University of Baltimore',
 'University of Bridgeport',
 'University of California, Berkeley',
 'University of California, Davis',
 'University of California, Irvine',
 'University of California, Los Angeles',
 'University of California, Merced',
 'University of California, Riverside',
 'University of California, San Diego',
 'University of California, Santa Barbara',
 'University of California, Santa Cruz',
 'University of Central Arkansas',
 'University of Central Florida',
 'University of Central Missouri',
 'University of Central Oklahoma',
 'University of Charleston',
 'University of Chicago',
 'University of Cincinnati',
 'University of Colorado Boulder',
 'University of Colorado Colorado Springs',
 'University of Colorado Denver',
 'University of Connecticut',
 'University of Dallas',
 'University of Dayton',
 'University of Delaware',
 'University of Denver',
 'University of Detroit Mercy',
 'University of Dubuque',
 'University of Evansville',
 'University of Findlay',
 'University of Florida',
 'University of Georgia',
 'University of Great Falls',
 'University of Hartford',
 'University of Hawaii at Hilo',
 'University of Hawaii at Manoa',
 'University of Houston',
 'University of Houston - Downtown',
 'University of Idaho',
 'University of Illinois at Chicago',
 'University of Illinois at Springfield',
 'University of Illinois at Urbana-Champaign',
 'University of Indianapolis',
 'University of Iowa',
 'University of Kansas',
 'University of Kentucky',
 'University of La Verne',
 'University of Louisiana at Lafayette',
 'University of Louisiana at Monroe',
 'University of Louisville',
 'University of Maine',
 'University of Maine at Farmington',
 'University of Maine at Machias',
 'University of Maine at Presque Isle',
 'University of Mary',
 'University of Mary Hardin-Baylor',
 'University of Mary Washington',
 'University of Maryland',
 'University of Maryland Baltimore County',
 'University of Maryland Eastern Shore',
 'University of Maryland University College',
 'University of Massachusetts Amherst',
 'University of Massachusetts Boston',
 'University of Massachusetts Dartmouth',
 'University of Massachusetts Lowell',
 'University of Memphis',
 'University of Miami',
 'University of Michigan',
 'University of Michigan - Dearborn',
 'University of Michigan - Flint',
 'University of Minnesota, Crookston',
 'University of Minnesota, Duluth',
 'University of Minnesota, Morris',
 'University of Minnesota, Twin Cities',
 'University of Mississippi',
 'University of Mississippi Medical Center',
 'University of Missouri - Columbia',
 'University of Missouri - Kansas City',
 'University of Missouri - St. Louis',
 'University of Mobile',
 'University of Montana',
 'University of Montevallo',
 'University of Mount Union',
 'University of Nebraska - Kearney',
 'University of Nebraska - Lincoln',
 'University of Nebraska - Omaha',
 'University of Nevada, Las Vegas',
 'University of Nevada, Reno',
 'University of New England',
 'University of New Hampshire',
 'University of New Hampshire at Manchester',
 'University of New Haven',
 'University of New Mexico',
 'University of New Orleans',
 'University of North Alabama',
 'University of North Carolina School of the Arts',
 'University of North Carolina at Asheville',
 'University of North Carolina at Chapel Hill',
 'University of North Carolina at Charlotte',
 'University of North Carolina at Greensboro',
 'University of North Carolina at Pembroke',
 'University of North Carolina at Wilmington',
 'University of North Dakota',
 'University of North Florida',
 'University of North Georgia',
 'University of North Texas',
 'University of Northern Colorado',
 'University of Northern Iowa',
 'University of Northwestern St. Paul',
 'University of Notre Dame',
 'University of Oklahoma',
 'University of Oregon',
 'University of Pennsylvania',
 'University of Phoenix',
 'University of Pikeville',
 'University of Pittsburgh',
 'University of Pittsburgh at Bradford',
 'University of Pittsburgh at Greensburg',
 'University of Pittsburgh at Johnstown',
 'University of Portland',
 'University of Puerto Rico at Mayaguez',
 'University of Puerto Rico at Rio Piedras',
 'University of Puget Sound',
 'University of Redlands',
 'University of Rhode Island',
 'University of Richmond',
 'University of Rochester',
 'University of Saint Joseph',
 'University of San Diego',
 'University of San Francisco',
 'University of Scranton',
 'University of Sioux Falls',
 'University of South Alabama',
 'University of South Carolina',
 'University of South Carolina Aiken',
 'University of South Carolina Beaufort',
 'University of South Carolina Upstate',
 'University of South Dakota',
 'University of South Florida',
 'University of South Florida - Saint Petersburg',
 'University of Southern California',
 'University of Southern Indiana',
 'University of Southern Maine',
 'University of Southern Mississippi',
 'University of St. Francis',
 'University of St. Thomas',
 'University of Tampa',
 'University of Tennessee',
 'University of Tennessee at Chattanooga',
 'University of Tennessee at Martin',
 'University of Texas at Arlington',
 'University of Texas at Austin',
 'University of Texas at Dallas',
 'University of Texas at El Paso',
 'University of Texas at San Antonio',
 'University of Texas at Tyler',
 'University of Texas of the Permian Basin',
 'University of Toledo',
 'University of Tulsa',
 'University of Utah',
 'University of Vermont',
 'University of Virginia',
 "University of Virginia's College at Wise",
 'University of Washington',
 'University of Washington Bothell',
 'University of Washington Tacoma',
 'University of West Alabama',
 'University of West Florida',
 'University of West Georgia',
 'University of Wisconsin - Eau Claire',
 'University of Wisconsin - Green Bay',
 'University of Wisconsin - La Crosse',
 'University of Wisconsin - Madison',
 'University of Wisconsin - Milwaukee',
 'University of Wisconsin - Oshkosh',
 'University of Wisconsin - Parkside',
 'University of Wisconsin - Platteville',
 'University of Wisconsin - River Falls',
 'University of Wisconsin - Stevens Point',
 'University of Wisconsin - Stout',
 'University of Wisconsin - Superior',
 'University of Wisconsin - Whitewater',
 'University of Wyoming',
 'University of the Arts',
 'University of the Cumberlands',
 'University of the Incarnate Word',
 'University of the Pacific',
 'University of the Sciences',
 'University of the Virgin Islands',
 'Urbana University',
 'Ursinus College',
 'Ursuline College',
 'Utah State University',
 'Utah Valley University',
 'Utica College',
 'Valdosta State University',
 'Valparaiso University',
 'Vanderbilt University',
 'Vanguard University of Southern California',
 'Vassar College',
 'Vaughn College of Aeronautics and Technology',
 'Villanova University',
 'Virginia Commonwealth University',
 'Virginia Military Institute',
 'Virginia Polytechnic Institute and State University',
 'Virginia State University',
 'Virginia Union University',
 'Virginia University of Lynchburg',
 'Virginia Wesleyan College',
 'Viterbo University',
 'Voorhees College',
 'Wabash College',
 'Wagner College',
 'Wake Forest University',
 'Waldorf College',
 'Walla Walla University',
 'Walsh University',
 'Warner Pacific College',
 'Warner University',
 'Warren Wilson College',
 'Wartburg College',
 'Washburn University',
 'Washington & Jefferson College',
 'Washington Adventist University',
 'Washington College',
 'Washington State University',
 'Washington University in St. Louis',
 'Washington and Lee University',
 'Wayne State College',
 'Wayne State University',
 'Waynesburg University',
 'Webb Institute',
 'Weber State University',
 'Webster University',
 'Wellesley College',
 'Wells College',
 'Wentworth Institute of Technology',
 'Wesley College',
 'Wesleyan College',
 'Wesleyan University',
 'West Chester University of Pennsylvania',
 'West Liberty University',
 'West Texas A&M University',
 'West Virginia State University',
 'West Virginia University',
 'West Virginia Wesleyan College',
 'Western Carolina University',
 'Western Connecticut State University',
 'Western Governors University',
 'Western Illinois University',
 'Western Kentucky University',
 'Western Michigan University',
 'Western New England University',
 'Western New Mexico University',
 'Western State Colorado University',
 'Western Washington University',
 'Westfield State University',
 'Westminster College',
 'Westmont College',
 'Wheaton College',
 'Wheeling Jesuit University',
 'Wheelock College',
 'Whitman College',
 'Whittier College',
 'Whitworth University',
 'Wichita State University',
 'Widener University',
 'Wilberforce University',
 'Wiley College',
 'Wilkes University',
 'Willamette University',
 'William Jessup University',
 'William Jewell College',
 'William Paterson University',
 'William Peace University',
 'William Penn University',
 'William Woods University',
 'Williams College',
 'Wilmington College',
 'Wilmington University',
 'Wilson College',
 'Wingate University',
 'Winona State University',
 'Winston-Salem State University',
 'Winthrop University',
 'Wittenberg University',
 'Wofford College',
 'Woodbury University',
 'Worcester Polytechnic Institute',
 'Worcester State University',
 'Wright State University',
 'Xavier University',
 'Xavier University of Louisiana',
 'Yale University',
 'Yeshiva University',
 'York College',
 'York College of Pennsylvania',
 'Youngstown State University'
 ]

school_loc_list = [
            'Alabama',
            'Alaska',
            'Arizona',
            'Arkansas',
            'California',
            'Colorado',
            'Connecticut',
            'Delaware',
            'District of Columbia',
            'Florida',
            'Georgia',
            'Guam',
            'Hawaii',
            'Idaho',
            'Illinois',
            'Indiana',
            'Iowa',
            'Kansas',
            'Kentucky',
            'Louisiana',
            'Maine',
            'Maryland',
            'Massachusetts',
            'Michigan',
            'Minnesota',
            'Mississippi',
            'Missouri',
            'Montana',
            'Nebraska',
            'Nevada',
            'New Hampshire',
            'New Jersey',
            'New Mexico',
            'New York',
            'North Carolina',
            'North Dakota',
            'Ohio',
            'Oklahoma',
            'Oregon',
            'Other',
            'Pennsylvania',
            'Puerto Rico',
            'Rhode Island',
            'South Carolina',
            'South Dakota',
            'Tennessee',
            'Texas',
            'Utah',
            'Vermont',
            'Virgin Islands',
            'Virginia',
            'Washington',
            'West Virginia',
            'Wisconsin',
            'Wyoming',

        ]
